services:
  kaladin:
    image: kaladin:latest
    ports:
      - "6550:6550"
    volumes:
      - "/tmp/data/in:/data/in"
      - "/tmp/data/out:/data/out"
      - "/tmp/jars:/jars"
    environment:
      BRIDGEFOUR_HOST: 0.0.0.0
      BRIDGEFOUR_PORT: 6550
      WORKER1_HOST: spren-01
      WORKER1_PORT: 6551
      WORKER2_HOST: spren-02
      WORKER2_PORT: 6552
    networks:
      - bridgefour
    depends_on:
      - spren-01
      - spren-02
      - spren-03

  spren-01:
    image: spren:latest
    ports:
      - "6551:6551"
    volumes:
      - "/tmp/data/in:/data/in"
      - "/tmp/data/out:/data/out"
      - "/tmp/jars:/jars"
    environment:
      WORKER_ID: 1
      BRIDGEFOUR_HOST: 0.0.0.0
      BRIDGEFOUR_PORT: 6551
      LEADER_HOST: kaladin
      LEADER_PORT: 6550
    networks:
      - bridgefour

  spren-02:
    image: spren:latest
    ports:
      - "6552:6552"
    volumes:
      - "/tmp/data/in:/data/in"
      - "/tmp/data/out:/data/out"
      - "/tmp/jars:/jars"
    environment:
      WORKER_ID: 2
      BRIDGEFOUR_HOST: 0.0.0.0
      BRIDGEFOUR_PORT: 6552
      LEADER_HOST: kaladin
      LEADER_PORT: 6550
    networks:
      - bridgefour
  # Unused until addWorker is called
  spren-03:
    image: spren:latest
    ports:
      - "6553:6553"
    volumes:
      - "/tmp/data/in:/data/in"
      - "/tmp/data/out:/data/out"
      - "/tmp/jars:/jars"
    environment:
      WORKER_ID: 3
      BRIDGEFOUR_HOST: 0.0.0.0
      BRIDGEFOUR_PORT: 6553
      LEADER_HOST: kaladin
      LEADER_PORT: 6550
    networks:
      - bridgefour

networks:
  bridgefour:
    driver: bridge
